"""Type stubs for sexpdata -- only the API surface used by this project."""

from typing import Any

class Symbol(str):
    def value(self) -> str: ...
    def quote(self) -> str: ...
    def unquote(self) -> str: ...

class Quoted:
    x: list[Any]
    def __init__(self, x: object) -> None: ...

def loads(string: str, **kwds: object) -> list[Any]: ...
def dumps(obj: object, **kwds: object) -> str: ...

class ExpectClosingBracket(Exception): ...
class ExpectNothing(Exception): ...
class ExpectSExp(Exception): ...
